modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Flanks255/simplylight/issues"
[[mods]]
modId="simplybackpacks"
version="${file.jarVersion}"
displayName="Simply Backpacks"
logoFile="sblogo.png"
credits=""
authors="Flanks255"
description='''
'''
[[dependencies.simplybackpacks]]
modId="forge"
mandatory=true
versionRange="[47.0.0,)"
ordering="NONE"
side="BOTH"