modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory (24 is current forge version)
license="MIT"
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="simplybackpacks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Simply Backpacks" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="sblogo.png" #optional
credits="" #optional
authors="Flanks255" #optional
#description='''
#'''

[[dependencies.simplybackpacks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"