modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="simplybackpacks"
version="${file.jarVersion}"
displayName="Simply Backpacks"
logoFile="sblogo.png"
credits=""
authors="Flanks255"
description='''
'''