modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
issueTrackerURL="https://github.com/Flanks255/simplylight/issues"
[[mods]]
modId="simplybackpacks"
version="${file.jarVersion}"
displayName="Simply Backpacks"
logoFile="sblogo.png"
credits=""
authors="Flanks255"
description='''
'''
