modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/Flanks255/simplylight/issues"
[[mods]]
modId="simplybackpacks"
version="${file.jarVersion}"
displayName="Simply Backpacks"
logoFile="sblogo.png"
credits=""
authors="Flanks255"
description='''
'''
[[dependencies.simplybackpacks]]
modId="neoforge"
required=true
versionRange="[21.0,)"
ordering="NONE"
side="BOTH"